#ifndef SIM_HPP
#define SIM_HPP

#include "structs.hpp"
using namespace std;

void simulate_all_params(input_params&, rates& , sim_data&, parameters&, ofstream*);
double simulate_param_set(int , input_params& , sim_data&, rates& , con_levels&, con_levels&);
bool calculate_concentrations(input_params&, con_levels&, rates&, sim_data&);
void find_GRB(double* , con_levels& , int, double);
void findG (double * , con_levels& , int, double );
void findGRSRB (double*, con_levels&, int, double);
void findGRS(double *, con_levels&, int, double);
void findGCR (double * , con_levels& , int, double );
void findGC(double* , con_levels& , int, double);
void findGBR(double* , con_levels& , int, double);
void findGB(double* , con_levels&  , int, double );
void findGBRB(double* ,con_levels& , int, double );
void findGBB(double * , con_levels&, int, double);
void findMNPO(double* , con_levels& , int, int, double);
void findMCPO(double* , con_levels& , int, double);
void findMNPT(double* , con_levels&, int, double);
void findMCPT(double* , con_levels& , int , int, double );
void findMNRT(double* , con_levels&, int, double);
void findMCRT(double* , con_levels& , int, double);
void findMNREV(double* , con_levels&, int, double);
void findMCREV(double* , con_levels& , int, double);
void findMNRO(double* , con_levels& , int, double);
void findMCRO(double*, con_levels& , int, double);
void findMNB(double *, con_levels&, int, double);
void findMCB(double* , con_levels& , int, double);
void findMNNP(double* , con_levels& , int, double);
void findMCNP(double* , con_levels& , int, double);
void findB(double* , con_levels& , int, double);
void findCL (double* , con_levels& , int, double);
void findBC(double*, con_levels& , int, double);
void findCYREV(double*, con_levels& , int, double);
void findREVN(double * , con_levels& , int, double);
void findCYREVG(double* , con_levels&, int, double);
void findREVNG(double* , con_levels&, int, double);
void findCYREVGP(double*, con_levels&, int, double);
void findREVNGP(double *, con_levels&, int, double);
void findCYREVP(double*, con_levels&, int, double);
void findREVNP(double* , con_levels& , int, double);
void findGTO(double* , con_levels& , int, double);

void findX00001(double*, con_levels&, int, double);
void findX00011(double*, con_levels&, int, double);
void findX00100(double*, con_levels&, int, double);
void findX00110(double*, con_levels&, int, double);
void findX00200(double*, con_levels&, int, double);
void findX00210(double*, con_levels&, int, double);
void findX01000(double*, con_levels&, int, double);
void findX01010(double*, con_levels&, int, double);
void findX01011(double*, con_levels&, int, double);
void findX02000(double*, con_levels&, int, double);
void findX02010(double*, con_levels&, int, double);
void findX02011(double*, con_levels&, int, double);

void findX10000(double*, con_levels&, int, double);
void findX10100(double*, con_levels&, int, double);

void findX20000(double*, con_levels&, int, double);
void findX20010(double*, con_levels&, int, double);
void findX20011(double*, con_levels&, int, double);
void findX20100(double*, con_levels&, int, double);
void findX20110(double*, con_levels&, int, double);
void findX20111(double*, con_levels&, int, double);
void findX21000(double*, con_levels&, int, double);
void findX21010(double*, con_levels&, int, double);
void findX21011(double*, con_levels&, int, double);
void findX21100(double*, con_levels&, int, double);
void findX21110(double*, con_levels&, int, double);
void findX21111(double*, con_levels&, int, double);
void findX22000(double*, con_levels&, int, double);
void findX22010(double*, con_levels&, int, double);
void findX22011(double*, con_levels&, int, double);
void findX22100(double*, con_levels&, int, double);
void findX22110(double*, con_levels&, int, double);
void findX22111(double*, con_levels&, int, double);

void findX30000(double*, con_levels&, int, double);
void findX30100(double*, con_levels&, int, double);
void findX30200(double*, con_levels&, int, double);
void findX30300(double*, con_levels&, int, double);

void findX40000(double*, con_levels&, int, double);
void findX40010(double*, con_levels&, int, double);
void findX40011(double*, con_levels&, int, double);
void findX40100(double*, con_levels&, int, double);
void findX40110(double*, con_levels&, int, double);
void findX40111(double*, con_levels&, int, double);
void findX40200(double*, con_levels&, int, double);
void findX40210(double*, con_levels&, int, double);
void findX40211(double*, con_levels&, int, double);
void findX40300(double*, con_levels&, int, double);
void findX40310(double*, con_levels&, int, double);
void findX40311(double*, con_levels&, int, double);
void findX41000(double*, con_levels&, int, double);
void findX41010(double*, con_levels&, int, double);
void findX41011(double*, con_levels&, int, double);
void findX41100(double*, con_levels&, int, double);
void findX41110(double*, con_levels&, int, double);
void findX41111(double*, con_levels&, int, double);
void findX41200(double*, con_levels&, int, double);
void findX41210(double*, con_levels&, int, double);
void findX41211(double*, con_levels&, int, double);
void findX41300(double*, con_levels&, int, double);
void findX41310(double*, con_levels&, int, double);
void findX41311(double*, con_levels&, int, double);
void findX42000(double*, con_levels&, int, double);
void findX42010(double*, con_levels&, int, double);
void findX42011(double*, con_levels&, int, double);
void findX42100(double*, con_levels&, int, double);
void findX42110(double*, con_levels&, int, double);
void findX42111(double*, con_levels&, int, double);
void findX42200(double*, con_levels&, int, double);
void findX42210(double*, con_levels&, int, double);
void findX42211(double*, con_levels&, int, double);
void findX42300(double*, con_levels&, int, double);
void findX42310(double*, con_levels&, int, double);
void findX42311(double*, con_levels&, int, double);

void findX50000(double*, con_levels&, int, double);
void findX50010(double*, con_levels&, int, double);
void findX50011(double*, con_levels&, int, double);
void findX50100(double*, con_levels&, int, double);
void findX50110(double*, con_levels&, int, double);
void findX50111(double*, con_levels&, int, double);
void findX50200(double*, con_levels&, int, double);
void findX50210(double*, con_levels&, int, double);
void findX50211(double*, con_levels&, int, double);
void findX50300(double*, con_levels&, int, double);
void findX50310(double*, con_levels&, int, double);
void findX50311(double*, con_levels&, int, double);

void findX51000(double*, con_levels&, int, double);
void findX51010(double*, con_levels&, int, double);
void findX51011(double*, con_levels&, int, double);
void findX51100(double*, con_levels&, int, double);
void findX51110(double*, con_levels&, int, double);
void findX51111(double*, con_levels&, int, double);
void findX51200(double*, con_levels&, int, double);
void findX51210(double*, con_levels&, int, double);
void findX51211(double*, con_levels&, int, double);
void findX51300(double*, con_levels&, int, double);
void findX51310(double*, con_levels&, int, double);
void findX51311(double*, con_levels&, int, double);

void findX52000(double*, con_levels&, int, double);
void findX52010(double*, con_levels&, int, double);
void findX52011(double*, con_levels&, int, double);
void findX52100(double*, con_levels&, int, double);
void findX52110(double*, con_levels&, int, double);
void findX52111(double*, con_levels&, int, double);
void findX52200(double*, con_levels&, int, double);
void findX52210(double*, con_levels&, int, double);
void findX52211(double*, con_levels&, int, double);
void findX52300(double*, con_levels&, int, double);
void findX52310(double*, con_levels&, int, double);
void findX52311(double*, con_levels&, int, double);

void findX60000(double*, con_levels&, int, double);
void findX60010(double*, con_levels&, int, double);
void findX60011(double*, con_levels&, int, double);
void findX60100(double*, con_levels&, int, double);
void findX60110(double*, con_levels&, int, double);
void findX60111(double*, con_levels&, int, double);
void findX60200(double*, con_levels&, int, double);
void findX60210(double*, con_levels&, int, double);
void findX60211(double*, con_levels&, int, double);
void findX60300(double*, con_levels&, int, double);
void findX60310(double*, con_levels&, int, double);
void findX60311(double*, con_levels&, int, double);

void findX61000(double*, con_levels&, int, double);
void findX61010(double*, con_levels&, int, double);
void findX61011(double*, con_levels&, int, double);
void findX61100(double*, con_levels&, int, double);
void findX61110(double*, con_levels&, int, double);
void findX61111(double*, con_levels&, int, double);
void findX61200(double*, con_levels&, int, double);
void findX61210(double*, con_levels&, int, double);
void findX61211(double*, con_levels&, int, double);
void findX61300(double*, con_levels&, int, double);
void findX61310(double*, con_levels&, int, double);
void findX61311(double*, con_levels&, int, double);

void findX62000(double*, con_levels&, int, double);
void findX62010(double*, con_levels&, int, double);
void findX62011(double*, con_levels&, int, double);
void findX62100(double*, con_levels&, int, double);
void findX62110(double*, con_levels&, int, double);
void findX62111(double*, con_levels&, int, double);
void findX62200(double*, con_levels&, int, double);
void findX62210(double*, con_levels&, int, double);
void findX62211(double*, con_levels&, int, double);
void findX62300(double*, con_levels&, int, double);
void findX62310(double*, con_levels&, int, double);
void findX62311(double*, con_levels&, int, double);

void findLTN(double*, con_levels&, int, double);
#endif
